import Link from 'next/link';

export default function PrivacyPage() {
  return (
    <main style={{ minHeight: '100vh', background: 'var(--bg)', paddingTop: '100px', paddingBottom: '100px' }}>
      <div className="container" style={{ maxWidth: '800px' }}>
        <h1 style={{ fontSize: '2.5rem', marginBottom: '2rem' }}>Privacy <span className="text-gradient">Policy</span></h1>
        <div className="glass-card" style={{ padding: '3rem', lineHeight: '1.8', opacity: 0.9 }}>
          <p>Last Updated: March 2026</p>
          <h2 style={{ fontSize: '1.5rem', marginTop: '2rem', marginBottom: '1rem' }}>1. Information We Collect</h2>
          <p>When you use SiteSpark or visit a site generated by our platform, we may collect information you provide directly via contact forms, such as your name, email address, and phone number.</p>
          
          <h2 style={{ fontSize: '1.5rem', marginTop: '2rem', marginBottom: '1rem' }}>2. How We Use Your Information</h2>
          <p>We use the collected information to facilitate communication between website owners and their visitors, to provide and improve our services, and to ensure a secure experience.</p>
          
          <h2 style={{ fontSize: '1.5rem', marginTop: '2rem', marginBottom: '1rem' }}>3. Data Storage</h2>
          <p>Your data is stored securely using industry-standard encryption and professional cloud infrastructure (Supabase/PostgreSQL).</p>
        </div>
        <div style={{ marginTop: '2rem' }}>
          <Link href="/" style={{ color: 'var(--primary)', textDecoration: 'none', fontWeight: 700 }}>&larr; Back to Home</Link>
        </div>
      </div>
    </main>
  );
}
